source 'http://rubygems.org'

gem 'sinatra'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'thin'
gem 'shotgun'
gem 'sqlite3', :group => 'development'
gem 'pg', :group => 'production'
gem 'pony'
gem 'tux'
gem 'pry'